# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wgDiV8Y_BWssz3p8Ovlpg-EWEHFOB7NG
"""

print("Welcome to Python")

X = int(input("Enter the first Integer: "))
Y = int(input("Enter the second Integer: "))
Z = X * Y
print("X:", X)
print("Y:", Y)
print("Z:", Z)