# -*- coding: utf-8 -*-
"""bfs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ZKZ8A6VhK8ha_JeOI6fzV5_IIYHyiH2
"""

def bfs(graph, start, path = []):
  queue = [start]
  while queue:
    vertex = queue.pop(0)
    if vertex not in path:
      path = path + [vertex]
      queue = queue + graph[vertex]
  return path


if __name__ == '__main__':

  graph = {'A':['B','C','D'],
           'B':['E'],
           'C':['F','G'],
           'D':['H'],
           'E':['I'],
           'F':['J'],
           'G':[],
           'H':[],
           'I':[],
           'J':[]}

print('bfs: ', bfs(graph, 'A'))