# -*- coding: utf-8 -*-
"""problem_05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gvuPV3duJTDmROKmBGGYbVgtJUuV259W
"""

'''
Take an integer value as input and determine whether it is an even or odd number. Therefore, print an appropriate message (even/odd).
'''

num = int(input("Enter an Integer: "))

if num % 2 == 0:
    print(num, "is EVEN!.")
else:
    print(num, "is ODD!.")