# -*- coding: utf-8 -*-
"""problem_18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15A7w2RNOhvJo-X-_D-ixRjm0M8q0h2Ke
"""

'''
Define a function that receives a list of values and print all values of the odd indices.
'''

def print_odd_index_values(numbers):
  for ind, val in enumerate(numbers):
    if ind%2 != 0:
      print(val, end=" ")

  print()

print_odd_index_values([1,2,3,4,5,6,7,8,9,10])