# -*- coding: utf-8 -*-
"""problem_04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xh-T7fnBJ66H8s5n43u9VcyFvCU4zN9q
"""

'''
Write a Python program to print a value without a newline or space.
'''

print("Hello", end="")
print("AI")