# -*- coding: utf-8 -*-
"""problem_07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G18U9ij-8vI7HSPQ70ePXDqsHQcToZU3
"""

'''
Write a Python program to print all even numbers from a given list of numbers in the same order.
'''

myList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
for i in myList:
    if i % 2 == 0 :
        print(i)