# -*- coding: utf-8 -*-
"""problem_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wgDiV8Y_BWssz3p8Ovlpg-EWEHFOB7NG
"""

'''
Take two integer values as input and store them in two variables named X and Y. Multiply these two values and store the result in another variable named Z. Print the values of the variables: X, Y and Z.
Input() – is used to take input.
Print() – is used to print a value.
'''

X = int(input("Enter the first Integer: "))
Y = int(input("Enter the second Integer: "))
Z = X * Y
print("X: ", X)
print("Y: ", Y)
print("Z: ", Z)